C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\distributions.py:515: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains [64, 32, 16] which is of type list.
  warnings.warn(message)
C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\distributions.py:515: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains [128, 64, 32] which is of type list.
  warnings.warn(message)
C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\distributions.py:515: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains [256, 128, 64] which is of type list.
  warnings.warn(message)
C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\distributions.py:515: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains [512, 256, 128, 64] which is of type list.
  warnings.warn(message)
[33m[W 2025-02-24 09:21:55,074][0m Trial 0 failed with parameters: {'learning_rate': 0.0009497635950522362, 'weight_decay': 0.00035722094632923296, 'latent_dim': 5, 'hidden_dims': [128, 64, 32], 'activation': 'relu'} because of the following error: OSError(22, 'Invalid argument').[0m
Traceback (most recent call last):
  File "C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 310, in objective
    synthetic_loader = get_pyg_loader(config["data_folder"], batch_size=config.get("batch_size", 1), shuffle=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 148, in get_pyg_loader
    data_list = create_pyg_dataset(folder_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 111, in create_pyg_dataset
    nx_graphs, graph_features, _ = load_graph_data(folder_path)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 42, in load_graph_data
    with open(graph_features_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'r"C:\\Users\\denni\\Documents\\thesis_dnr_gnn_dev\\model_search\\data\\1739737645.4646165"\\graph_features.pkl'
[33m[W 2025-02-24 09:21:55,079][0m Trial 0 failed with value None.[0m
Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 322, in <module>
    study.optimize(objective, n_trials=config.get("hp_search_n_trials", 50), callbacks=[optuna.integration.WeightsAndBiasesCallback(metric_name="val_loss_synthetic")])
  File "C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\study\study.py", line 475, in optimize
    _optimize(
  File "C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\study\_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\study\_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\study\_optimize.py", line 248, in _run_trial
    raise func_err
  File "C:\Users\denni\AppData\Local\pypoetry\Cache\virtualenvs\dnr-gnn-sOrvVjlK-py3.12\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 310, in objective
    synthetic_loader = get_pyg_loader(config["data_folder"], batch_size=config.get("batch_size", 1), shuffle=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 148, in get_pyg_loader
    data_list = create_pyg_dataset(folder_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 111, in create_pyg_dataset
    nx_graphs, graph_features, _ = load_graph_data(folder_path)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\first_model.py", line 42, in load_graph_data
    with open(graph_features_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'r"C:\\Users\\denni\\Documents\\thesis_dnr_gnn_dev\\model_search\\data\\1739737645.4646165"\\graph_features.pkl'
