2025-04-22 23:10:33,563 INFO Sampled n_busses -> 40
2025-04-22 23:14:40,114 INFO Sampled n_busses -> 30
2025-04-22 23:21:49,712 INFO Sampled n_busses -> 35
2025-04-22 23:24:18,105 INFO Sampled n_busses -> 30
2025-04-22 23:26:08,427 INFO Sampled n_busses -> 36
2025-04-22 23:30:26,949 INFO Sampled n_busses -> 40
2025-04-23 10:44:10,905 INFO Sampled n_busses -> 35
2025-04-23 15:16:12,174 INFO Sampled n_busses -> 35
2025-04-23 15:24:56,227 INFO Sampled n_busses -> 39
2025-04-28 10:37:59,880 INFO Total graphs to be generated: 2
2025-04-28 10:45:10,333 INFO Total graphs to be generated: 2
2025-04-28 10:47:07,693 INFO Total graphs to be generated: 2
2025-04-28 10:47:07,696 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:47:07,699 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:47:07,699 INFO Processing summary: Total: 2, Successful: 0, Failed: 2
2025-04-28 10:47:07,699 INFO Transformation process completed.
2025-04-28 10:47:07,699 INFO Processing summary: {'total': 2, 'successful': 0, 'failed': 2}
2025-04-28 10:49:16,424 INFO Total graphs to be generated: 2
2025-04-28 10:49:16,424 INFO Saving results to data
2025-04-28 10:49:16,426 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:49:16,429 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:49:16,429 INFO Processing summary: Total: 2, Successful: 0, Failed: 2
2025-04-28 10:49:16,429 INFO Transformation process completed.
2025-04-28 10:50:28,710 INFO Total graphs to be generated: 2
2025-04-28 10:50:28,711 INFO Saving results to data
2025-04-28 10:50:28,713 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:50:28,716 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:50:28,716 INFO Processing summary: Total: 2, Successful: 0, Failed: 2
2025-04-28 10:50:28,716 INFO Transformation process completed.
2025-04-28 10:50:28,716 INFO Processing summary: {'total': 2, 'successful': 0, 'failed': 2}
2025-04-28 10:51:29,134 INFO Total graphs to be generated: 2
2025-04-28 10:51:29,134 INFO Saving results to data
2025-04-28 10:51:29,137 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:51:29,139 ERROR Error processing subgraph 0: 'Namespace' object has no attribute 'modify_subgraph_each_sample'
2025-04-28 10:51:29,139 INFO Processing summary: Total: 2, Successful: 0, Failed: 2
2025-04-28 10:51:29,140 INFO Transformation process completed.
2025-04-28 10:51:29,140 INFO Processing summary: {'total': 2, 'successful': 0, 'failed': 2}
2025-04-28 11:00:23,977 INFO Total graphs to be generated: 2
2025-04-28 11:00:23,978 INFO Saving results to data
2025-04-28 11:02:47,538 INFO Total graphs to be generated: 2
2025-04-28 11:02:47,539 INFO Saving results to data
2025-04-28 11:02:47,541 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:02:47,541 INFO Create new modified graph 
 ___________________________
2025-04-28 11:02:47,547 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:02:47,549 INFO Sampled n_switches -> 3
2025-04-28 11:02:47,549 INFO Sampled layer_list -> [0, 1]
2025-04-28 11:02:48,028 INFO cycles_added: 3
2025-04-28 11:02:48,028 INFO convex_layers_used: [0, 1]
2025-04-28 11:04:15,453 INFO Total graphs to be generated: 2
2025-04-28 11:04:15,453 INFO Saving results to data
2025-04-28 11:04:15,460 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:04:15,460 INFO Create new modified graph 
 ___________________________
2025-04-28 11:04:15,463 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:04:15,463 INFO Sampled n_switches -> 12
2025-04-28 11:04:15,463 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:04:16,168 INFO cycles_added: 12
2025-04-28 11:04:16,168 INFO convex_layers_used: [1, 2]
2025-04-28 11:04:23,179 INFO Sampled n_slack_busses -> 2
2025-04-28 11:04:23,630 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:04:27,386 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:04:27,386 INFO Create new modified graph 
 ___________________________
2025-04-28 11:04:27,389 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:04:27,389 INFO Sampled n_switches -> 3
2025-04-28 11:04:27,389 INFO Sampled layer_list -> [0, 1]
2025-04-28 11:04:28,132 INFO cycles_added: 3
2025-04-28 11:04:28,132 INFO convex_layers_used: [0, 1]
2025-04-28 11:04:30,778 INFO Sampled n_slack_busses -> 1
2025-04-28 11:04:31,299 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:04:31,428 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:04:31,429 INFO Transformation process completed.
2025-04-28 11:04:31,429 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:04:31,429 INFO Samples for n_switches: [12, 3]
2025-04-28 11:04:31,430 INFO Samples for layer_list: [[1, 2], [0, 1]]
2025-04-28 11:04:31,430 INFO Samples for n_slack_busses: [2, 1]
2025-04-28 11:04:31,430 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_3']
2025-04-28 11:26:55,548 INFO Total graphs to be generated: 2
2025-04-28 11:26:55,548 INFO Saving results to data
2025-04-28 11:26:55,551 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:26:55,551 INFO Create new modified graph 
 ___________________________
2025-04-28 11:26:55,554 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:26:55,554 INFO Sampled n_switches -> 6
2025-04-28 11:26:55,554 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:26:55,996 INFO cycles_added: 6
2025-04-28 11:26:55,996 INFO convex_layers_used: [1, 2]
2025-04-28 11:27:09,340 INFO Sampled n_slack_busses -> 1
2025-04-28 11:27:09,788 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:27:13,591 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:27:13,591 INFO Create new modified graph 
 ___________________________
2025-04-28 11:27:13,594 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:27:13,594 INFO Sampled n_switches -> 3
2025-04-28 11:27:13,594 INFO Sampled layer_list -> [0, 2, 3, 4]
2025-04-28 11:27:16,376 INFO cycles_added: 3
2025-04-28 11:27:16,376 INFO convex_layers_used: [0, 2, 3, 4]
2025-04-28 11:27:28,164 INFO Sampled n_slack_busses -> 2
2025-04-28 11:27:28,730 INFO Sampled standard_cables -> standard_cable_2
2025-04-28 11:27:28,879 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:27:28,880 INFO Transformation process completed.
2025-04-28 11:27:28,880 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:27:28,880 INFO Samples for n_switches: [6, 3]
2025-04-28 11:27:28,880 INFO Samples for layer_list: [[1, 2], [0, 2, 3, 4]]
2025-04-28 11:27:28,880 INFO Samples for n_slack_busses: [1, 2]
2025-04-28 11:27:28,880 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_2']
2025-04-28 11:28:09,241 INFO Total graphs to be generated: 2
2025-04-28 11:28:09,242 INFO Saving results to data
2025-04-28 11:28:09,244 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:28:09,244 INFO Create new modified graph 
 ___________________________
2025-04-28 11:28:09,247 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:28:09,247 INFO Sampled n_switches -> 9
2025-04-28 11:28:09,247 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:28:09,815 INFO cycles_added: 9
2025-04-28 11:28:09,815 INFO convex_layers_used: [1, 2]
2025-04-28 11:28:16,904 INFO Sampled n_slack_busses -> 2
2025-04-28 11:28:17,329 INFO Sampled standard_cables -> standard_cable_1
2025-04-28 11:28:20,457 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:28:20,457 INFO Create new modified graph 
 ___________________________
2025-04-28 11:28:20,461 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:28:20,461 INFO Sampled n_switches -> 3
2025-04-28 11:28:20,461 INFO Sampled layer_list -> [0, 2, 3, 4]
2025-04-28 11:28:23,410 INFO cycles_added: 3
2025-04-28 11:28:23,410 INFO convex_layers_used: [0, 2, 3, 4]
2025-04-28 11:28:30,584 INFO Sampled n_slack_busses -> 1
2025-04-28 11:28:31,123 INFO Sampled standard_cables -> standard_cable_1
2025-04-28 11:28:31,254 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:28:31,256 INFO Transformation process completed.
2025-04-28 11:28:31,256 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:28:31,256 INFO Samples for n_switches: [9, 3]
2025-04-28 11:28:31,256 INFO Samples for layer_list: [[1, 2], [0, 2, 3, 4]]
2025-04-28 11:28:31,257 INFO Samples for n_slack_busses: [2, 1]
2025-04-28 11:28:31,257 INFO Samples for standard_cables: ['standard_cable_1', 'standard_cable_1']
2025-04-28 11:29:51,461 INFO Total graphs to be generated: 2
2025-04-28 11:29:51,462 INFO Saving results to data
2025-04-28 11:29:51,466 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:29:51,466 INFO Create new modified graph 
 ___________________________
2025-04-28 11:29:51,469 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:29:51,469 INFO Sampled n_switches -> 3
2025-04-28 11:29:51,469 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:29:51,667 INFO cycles_added: 3
2025-04-28 11:29:51,668 INFO convex_layers_used: [1, 2]
2025-04-28 11:29:54,944 INFO Sampled n_slack_busses -> 1
2025-04-28 11:29:55,364 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:29:58,813 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:29:58,813 INFO Create new modified graph 
 ___________________________
2025-04-28 11:29:58,818 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:29:58,818 INFO Sampled n_switches -> 14
2025-04-28 11:29:58,818 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 11:30:01,623 INFO cycles_added: 14
2025-04-28 11:30:01,624 INFO convex_layers_used: [1, 2, 3]
2025-04-28 11:30:08,221 INFO Sampled n_slack_busses -> 1
2025-04-28 11:30:08,738 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:30:08,929 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:30:08,930 INFO Transformation process completed.
2025-04-28 11:30:08,930 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:30:08,930 INFO Samples for n_switches: [3, 14]
2025-04-28 11:30:08,930 INFO Samples for layer_list: [[1, 2], [1, 2, 3]]
2025-04-28 11:30:08,931 INFO Samples for n_slack_busses: [1, 1]
2025-04-28 11:30:08,931 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_3']
2025-04-28 11:30:48,459 INFO Total graphs to be generated: 2
2025-04-28 11:30:48,459 INFO Saving results to data
2025-04-28 11:30:48,461 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:30:48,461 INFO Create new modified graph 
 ___________________________
2025-04-28 11:30:48,464 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:30:48,464 INFO Sampled n_switches -> 3
2025-04-28 11:30:48,464 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:30:48,679 INFO cycles_added: 3
2025-04-28 11:30:48,679 INFO convex_layers_used: [1, 2]
2025-04-28 11:30:56,157 INFO Sampled n_slack_busses -> 4
2025-04-28 11:30:56,559 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:31:00,092 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:31:00,092 INFO Create new modified graph 
 ___________________________
2025-04-28 11:31:00,094 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:31:00,094 INFO Sampled n_switches -> 9
2025-04-28 11:31:00,094 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 11:31:02,033 INFO cycles_added: 9
2025-04-28 11:31:02,033 INFO convex_layers_used: [1, 2, 3]
2025-04-28 11:31:04,168 INFO Sampled n_slack_busses -> 2
2025-04-28 11:31:04,721 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:31:04,893 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:31:04,895 INFO Transformation process completed.
2025-04-28 11:31:04,895 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:31:04,895 INFO Samples for n_switches: [3, 9]
2025-04-28 11:31:04,895 INFO Samples for layer_list: [[1, 2], [1, 2, 3]]
2025-04-28 11:31:04,895 INFO Samples for n_slack_busses: [4, 2]
2025-04-28 11:31:04,895 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_3']
2025-04-28 11:32:52,027 INFO Total graphs to be generated: 2
2025-04-28 11:32:52,027 INFO Saving results to data
2025-04-28 11:32:52,030 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:32:52,030 INFO Create new modified graph 
 ___________________________
2025-04-28 11:32:52,036 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:32:52,036 INFO Sampled n_switches -> 3
2025-04-28 11:32:52,036 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:32:52,226 INFO cycles_added: 3
2025-04-28 11:32:52,226 INFO convex_layers_used: [1, 2]
2025-04-28 11:33:30,517 INFO Sampled n_slack_busses -> 3
2025-04-28 11:33:30,925 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:33:34,322 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:33:34,322 INFO Create new modified graph 
 ___________________________
2025-04-28 11:33:34,324 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:33:34,324 INFO Sampled n_switches -> 3
2025-04-28 11:33:34,324 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 11:33:34,910 INFO cycles_added: 3
2025-04-28 11:33:34,910 INFO convex_layers_used: [1, 2, 3]
2025-04-28 11:33:39,038 INFO Sampled n_slack_busses -> 3
2025-04-28 11:33:39,581 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:33:39,729 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:33:39,729 INFO Transformation process completed.
2025-04-28 11:33:39,731 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:33:39,731 INFO Samples for n_switches: [3, 3]
2025-04-28 11:33:39,731 INFO Samples for layer_list: [[1, 2], [1, 2, 3]]
2025-04-28 11:33:39,731 INFO Samples for n_slack_busses: [3, 3]
2025-04-28 11:33:39,731 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_3']
2025-04-28 11:34:24,393 INFO Total graphs to be generated: 2
2025-04-28 11:34:24,394 INFO Saving results to data
2025-04-28 11:34:24,397 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:34:24,397 INFO Create new modified graph 
 ___________________________
2025-04-28 11:34:24,400 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:34:24,400 INFO Sampled n_switches -> 6
2025-04-28 11:34:24,400 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:34:24,814 INFO cycles_added: 6
2025-04-28 11:34:24,814 INFO convex_layers_used: [1, 2]
2025-04-28 11:34:41,207 INFO Sampled n_slack_busses -> 2
2025-04-28 11:34:41,598 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:34:45,007 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:34:45,007 INFO Create new modified graph 
 ___________________________
2025-04-28 11:34:45,010 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:34:45,010 INFO Sampled n_switches -> 4
2025-04-28 11:34:45,010 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 11:34:45,885 INFO cycles_added: 4
2025-04-28 11:34:45,885 INFO convex_layers_used: [1, 2, 3]
2025-04-28 11:34:53,170 INFO Sampled n_slack_busses -> 1
2025-04-28 11:34:53,732 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:34:53,866 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:34:53,867 INFO Transformation process completed.
2025-04-28 11:34:53,868 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:34:53,868 INFO Samples for n_switches: [6, 4]
2025-04-28 11:34:53,868 INFO Samples for layer_list: [[1, 2], [1, 2, 3]]
2025-04-28 11:34:53,868 INFO Samples for n_slack_busses: [2, 1]
2025-04-28 11:34:53,868 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_3']
2025-04-28 11:35:33,793 INFO Total graphs to be generated: 2
2025-04-28 11:35:33,793 INFO Saving results to data
2025-04-28 11:35:33,795 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:35:33,795 INFO Create new modified graph 
 ___________________________
2025-04-28 11:35:33,799 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:35:33,799 INFO Sampled n_switches -> 6
2025-04-28 11:35:33,799 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:35:34,170 INFO cycles_added: 6
2025-04-28 11:35:34,170 INFO convex_layers_used: [1, 2]
2025-04-28 11:35:46,669 INFO Sampled n_slack_busses -> 2
2025-04-28 11:35:47,103 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:35:50,307 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:35:50,307 INFO Create new modified graph 
 ___________________________
2025-04-28 11:35:50,309 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:35:50,309 INFO Sampled n_switches -> 7
2025-04-28 11:35:50,309 INFO Sampled layer_list -> [0, 2, 3, 4]
2025-04-28 11:35:55,521 INFO cycles_added: 7
2025-04-28 11:35:55,521 INFO convex_layers_used: [0, 2, 3, 4]
2025-04-28 11:36:15,557 INFO Sampled n_slack_busses -> 1
2025-04-28 11:36:16,060 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:36:16,211 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:36:16,211 INFO Transformation process completed.
2025-04-28 11:36:16,212 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:36:16,212 INFO Samples for n_switches: [6, 7]
2025-04-28 11:36:16,213 INFO Samples for layer_list: [[1, 2], [0, 2, 3, 4]]
2025-04-28 11:36:16,213 INFO Samples for n_slack_busses: [2, 1]
2025-04-28 11:36:16,213 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_3']
2025-04-28 11:36:45,289 INFO Total graphs to be generated: 2
2025-04-28 11:36:45,289 INFO Saving results to data
2025-04-28 11:36:45,291 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:36:45,291 INFO Create new modified graph 
 ___________________________
2025-04-28 11:36:45,295 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:36:45,295 INFO Sampled n_switches -> 3
2025-04-28 11:36:45,295 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:36:45,531 INFO cycles_added: 3
2025-04-28 11:36:45,531 INFO convex_layers_used: [1, 2]
2025-04-28 11:36:52,594 INFO Sampled n_slack_busses -> 1
2025-04-28 11:36:53,011 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 11:36:56,812 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:36:56,812 INFO Create new modified graph 
 ___________________________
2025-04-28 11:36:56,816 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:36:56,816 INFO Sampled n_switches -> 3
2025-04-28 11:36:56,816 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 11:36:57,419 INFO cycles_added: 3
2025-04-28 11:36:57,420 INFO convex_layers_used: [1, 2, 3]
2025-04-28 11:37:01,034 INFO Sampled n_slack_busses -> 2
2025-04-28 11:37:01,594 INFO Sampled standard_cables -> standard_cable_2
2025-04-28 11:37:01,726 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:37:01,727 INFO Transformation process completed.
2025-04-28 11:37:01,727 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:37:01,727 INFO Samples for n_switches: [3, 3]
2025-04-28 11:37:01,727 INFO Samples for layer_list: [[1, 2], [1, 2, 3]]
2025-04-28 11:37:01,727 INFO Samples for n_slack_busses: [1, 2]
2025-04-28 11:37:01,727 INFO Samples for standard_cables: ['standard_cable_3', 'standard_cable_2']
2025-04-28 11:37:33,238 INFO Total graphs to be generated: 2
2025-04-28 11:37:33,238 INFO Saving results to data
2025-04-28 11:37:33,240 INFO Modifying subgraph 0 for sample 1
2025-04-28 11:37:33,240 INFO Create new modified graph 
 ___________________________
2025-04-28 11:37:33,243 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 11:37:33,243 INFO Sampled n_switches -> 8
2025-04-28 11:37:33,243 INFO Sampled layer_list -> [1, 2]
2025-04-28 11:37:33,698 INFO cycles_added: 8
2025-04-28 11:37:33,698 INFO convex_layers_used: [1, 2]
2025-04-28 11:37:42,491 INFO Sampled n_slack_busses -> 2
2025-04-28 11:37:42,909 INFO Sampled standard_cables -> standard_cable_1
2025-04-28 11:37:46,525 INFO Modifying subgraph 1 for sample 1
2025-04-28 11:37:46,525 INFO Create new modified graph 
 ___________________________
2025-04-28 11:37:46,527 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 11:37:46,527 INFO Sampled n_switches -> 10
2025-04-28 11:37:46,528 INFO Sampled layer_list -> [0, 2, 3, 4]
2025-04-28 11:37:53,900 INFO cycles_added: 10
2025-04-28 11:37:53,900 INFO convex_layers_used: [0, 2, 3, 4]
2025-04-28 11:37:59,946 INFO Sampled n_slack_busses -> 4
2025-04-28 11:38:00,494 INFO Sampled standard_cables -> standard_cable_1
2025-04-28 11:38:00,679 INFO Processing summary: Total: 2, Successful: 2, Failed: 0
2025-04-28 11:38:00,679 INFO Transformation process completed.
2025-04-28 11:38:00,679 INFO Processing summary: {'total': 2, 'successful': 2, 'failed': 0}
2025-04-28 11:38:00,680 INFO Samples for n_switches: [8, 10]
2025-04-28 11:38:00,680 INFO Samples for layer_list: [[1, 2], [0, 2, 3, 4]]
2025-04-28 11:38:00,680 INFO Samples for n_slack_busses: [2, 4]
2025-04-28 11:38:00,680 INFO Samples for standard_cables: ['standard_cable_1', 'standard_cable_1']
2025-04-28 11:56:28,956 INFO Saving results to data
2025-04-28 11:56:28,958 INFO Processing summary: Total: 0, Successful: 0, Failed: 0
2025-04-28 11:56:28,958 INFO Transformation process completed.
2025-04-28 12:44:51,405 INFO Saving results to data
2025-04-28 12:47:12,653 INFO Saving results to data
2025-04-28 12:47:55,692 INFO Saving results to data
2025-04-28 12:50:29,015 INFO Saving results to data
2025-04-28 12:50:35,129 ERROR Worker exception: Can't pickle local object 'initialize_distributions.<locals>.sample_from_distribution'
2025-04-28 12:50:35,505 ERROR Worker exception: Can't pickle local object 'initialize_distributions.<locals>.sample_from_distribution'
2025-04-28 12:50:39,930 ERROR Worker exception: Can't pickle local object 'initialize_distributions.<locals>.sample_from_distribution'
2025-04-28 12:50:42,446 ERROR Worker exception: Can't pickle local object 'initialize_distributions.<locals>.sample_from_distribution'
2025-04-28 12:50:43,407 ERROR Worker exception: Can't pickle local object 'initialize_distributions.<locals>.sample_from_distribution'
2025-04-28 12:50:44,295 INFO Finished: {'total': 5, 'successful': 0, 'failed': 5}
2025-04-28 13:32:51,583 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 13:35:08,176 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 13:35:41,841 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 13:51:24,077 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 13:51:30,505 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 929, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 13:51:33,122 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 929, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 13:51:35,010 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 929, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 13:51:35,914 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 13:57:58,557 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 13:58:05,132 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 929, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 13:58:07,860 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 929, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 13:58:09,691 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 929, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 13:58:10,562 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 14:01:12,131 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:01:18,583 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 936, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:01:21,450 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 936, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:01:23,262 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 936, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:01:24,133 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 14:04:49,953 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:04:56,381 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 937, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:04:59,056 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 937, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:05:00,492 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 937, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:05:01,444 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 14:11:25,652 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:11:32,145 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 939, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:11:35,076 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 939, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:11:36,782 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 939, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:11:37,645 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 14:13:32,037 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:13:39,111 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 943, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:13:42,264 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 943, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:13:44,598 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 943, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:13:45,667 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 14:15:20,733 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:15:27,147 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 949, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:15:29,799 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 949, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:15:31,443 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 949, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:15:32,395 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 14:17:25,904 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:17:25,923 INFO Modifying subgraph graph_2a9887adec5a413c93e3b6cbd0761250 for sample 1
2025-04-28 14:17:25,924 INFO Create new modified graph 
 ___________________________
2025-04-28 14:17:25,936 INFO initial cycles: 0, max cycle length: 195, max distance: 51.00052260517583
2025-04-28 14:17:25,937 INFO Sampled n_switches -> 7
2025-04-28 14:17:25,937 INFO Sampled layer_list -> [1, 2]
2025-04-28 14:17:28,363 INFO cycles_added: 7
2025-04-28 14:17:28,363 INFO convex_layers_used: [1, 2]
2025-04-28 14:17:33,561 INFO Sampled n_slack_busses -> 2
2025-04-28 14:17:34,332 ERROR Failed to create line 7399--8677:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:34,355 ERROR Failed to create line 8696--8687:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:34,355 ERROR Failed to create line 8696--8078:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:34,355 ERROR Failed to create line 8696--8077:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:34,358 ERROR Failed to create line 8697--8088:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:34,474 ERROR Failed to create line 8640--8654:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:34,593 ERROR Failed to create line 9183--8689:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:34,686 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 14:17:38,963 INFO Power flow failed for graph_2a9887adec5a413c93e3b6cbd0761250@2025-04-25 21:30:00
2025-04-28 14:17:38,970 INFO Modifying subgraph graph_96f5683fecfb4d15a7e0fbfb0931d6c7 for sample 1
2025-04-28 14:17:38,970 INFO Create new modified graph 
 ___________________________
2025-04-28 14:17:38,980 INFO initial cycles: 0, max cycle length: 213, max distance: 63.02775471167538
2025-04-28 14:17:38,980 INFO Sampled n_switches -> 3
2025-04-28 14:17:38,980 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 14:17:40,541 INFO cycles_added: 3
2025-04-28 14:17:40,542 INFO convex_layers_used: [1, 2, 3]
2025-04-28 14:17:43,770 INFO Sampled n_slack_busses -> 3
2025-04-28 14:17:44,469 ERROR Failed to create line 6178--5742:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:44,591 ERROR Failed to create line 5743--9180:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:44,631 ERROR Failed to create line 5801--7529:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:45,021 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 14:17:45,242 INFO [Worker 18336] Saving graph graph_96f5683fecfb4d15a7e0fbfb0931d6c7_mod_a to data\28042025_range-100-100_3\original\networkx_graphs
2025-04-28 14:17:45,258 INFO Modifying subgraph graph_a6a5af713d2a40e2855d59bf69aa43a7 for sample 1
2025-04-28 14:17:45,258 INFO Create new modified graph 
 ___________________________
2025-04-28 14:17:45,276 INFO initial cycles: 1, max cycle length: 289, max distance: 54.162502231715365
2025-04-28 14:17:45,276 INFO Sampled n_switches -> 3
2025-04-28 14:17:45,276 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 14:17:48,417 INFO cycles_added: 2
2025-04-28 14:17:48,417 INFO convex_layers_used: [1, 2, 3]
2025-04-28 14:17:50,601 INFO Sampled n_slack_busses -> 2
2025-04-28 14:17:51,612 ERROR Failed to create line 1200--9167:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:51,674 ERROR Failed to create line 5859--5371:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:52,175 INFO Sampled standard_cables -> standard_cable_1
2025-04-28 14:17:52,403 INFO [Worker 18336] Saving graph graph_a6a5af713d2a40e2855d59bf69aa43a7_mod_a to data\28042025_range-100-100_3\original\networkx_graphs
2025-04-28 14:17:52,406 INFO Modifying subgraph graph_a82e966a43d94d84a0539bd7482100d7 for sample 1
2025-04-28 14:17:52,406 INFO Create new modified graph 
 ___________________________
2025-04-28 14:17:52,407 INFO initial cycles: 0, max cycle length: 83, max distance: 24.281060355744863
2025-04-28 14:17:52,407 INFO Sampled n_switches -> 9
2025-04-28 14:17:52,407 INFO Sampled layer_list -> [0, 1, 2, 3]
2025-04-28 14:17:55,409 INFO cycles_added: 9
2025-04-28 14:17:55,409 INFO convex_layers_used: [0, 1, 2, 3]
2025-04-28 14:17:58,579 INFO Sampled n_slack_busses -> 3
2025-04-28 14:17:58,801 ERROR Failed to create line 1024--5047:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,805 ERROR Failed to create line 1025--5053:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,809 ERROR Failed to create line 1026--1008:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,845 ERROR Failed to create line 5044--1002:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,845 ERROR Failed to create line 5045--5054:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,878 ERROR Failed to create line 5052--5054:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,937 ERROR Failed to create line 1004--1010:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,949 ERROR Failed to create line 1007--1023:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:58,950 ERROR Failed to create line 1007--1017:Unknown: 'r_ohm_per_km'
2025-04-28 14:17:59,006 INFO Sampled standard_cables -> standard_cable_2
2025-04-28 14:17:59,153 INFO [Worker 18336] Saving graph graph_a82e966a43d94d84a0539bd7482100d7_mod_a to data\28042025_range-100-100_3\original\networkx_graphs
2025-04-28 14:17:59,157 INFO Modifying subgraph graph_1acd5e1243584b3d8d1e78ad86929b52 for sample 1
2025-04-28 14:17:59,157 INFO Create new modified graph 
 ___________________________
2025-04-28 14:17:59,159 INFO initial cycles: 0, max cycle length: 111, max distance: 20.366931948599145
2025-04-28 14:17:59,159 INFO Sampled n_switches -> 3
2025-04-28 14:17:59,159 INFO Sampled layer_list -> [0, 2, 3, 4]
2025-04-28 14:18:01,841 INFO cycles_added: 3
2025-04-28 14:18:01,841 INFO convex_layers_used: [0, 2, 3, 4]
2025-04-28 14:18:03,886 INFO Sampled n_slack_busses -> 1
2025-04-28 14:18:04,162 ERROR Failed to create line 4998--4988:Unknown: 'r_ohm_per_km'
2025-04-28 14:18:04,194 ERROR Failed to create line 5005--4988:Unknown: 'r_ohm_per_km'
2025-04-28 14:18:04,228 ERROR Failed to create line 4915--4859:Unknown: 'r_ohm_per_km'
2025-04-28 14:18:04,398 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 14:18:04,533 INFO [Worker 18336] Saving graph graph_1acd5e1243584b3d8d1e78ad86929b52_mod_a to data\28042025_range-100-100_3\original\networkx_graphs
2025-04-28 14:18:04,535 INFO Finished: {'total': 0, 'successful': 0, 'failed': 0}
2025-04-28 14:22:14,965 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:22:14,979 INFO Modifying subgraph graph_de9a2db724864e69b2781ecfcc173c20 for sample 1
2025-04-28 14:22:14,979 INFO Create new modified graph 
 ___________________________
2025-04-28 14:22:14,990 INFO initial cycles: 0, max cycle length: 195, max distance: 51.00052260517583
2025-04-28 14:22:14,990 INFO Sampled n_switches -> 3
2025-04-28 14:22:14,990 INFO Sampled layer_list -> [0, 2, 3, 4]
2025-04-28 14:22:58,752 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:23:05,065 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 951, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:23:06,980 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 951, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:23:09,467 ERROR Worker crashed
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _worker() missing 1 required positional argument: 'idx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\denni\Documents\thesis_dnr_gnn_dev\src\electrify_subgraph.py", line 951, in transform_subgraphs
    suc, fl = fut.result()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: _worker() missing 1 required positional argument: 'idx'
2025-04-28 14:23:10,326 INFO Finished: {'total': 3, 'successful': 0, 'failed': 3}
2025-04-28 14:30:31,135 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:31:48,723 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:33:04,923 INFO Saving results to data\28042025_range-100-100_3\original
2025-04-28 14:33:10,431 INFO Modifying subgraph graph_bc1b3edb1ff34ab18cdc18a02b3e031f for sample 1
2025-04-28 14:33:10,431 INFO Create new modified graph 
 ___________________________
2025-04-28 14:33:10,445 INFO initial cycles: 0, max cycle length: 195, max distance: 51.00052260517583
2025-04-28 14:33:10,445 INFO Sampled n_switches -> 8
2025-04-28 14:33:10,445 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 14:33:13,908 INFO Modifying subgraph graph_24298691593c42cebe8122816c146f32 for sample 1
2025-04-28 14:33:13,908 INFO Create new modified graph 
 ___________________________
2025-04-28 14:33:13,928 INFO initial cycles: 0, max cycle length: 213, max distance: 63.02775471167538
2025-04-28 14:33:13,928 INFO Sampled n_switches -> 10
2025-04-28 14:33:13,928 INFO Sampled layer_list -> [1, 2, 3]
2025-04-28 14:33:17,216 INFO Modifying subgraph graph_73b564305f5d45eb8434b01590134a55 for sample 1
2025-04-28 14:33:17,216 INFO Create new modified graph 
 ___________________________
2025-04-28 14:33:17,240 INFO initial cycles: 1, max cycle length: 289, max distance: 54.162502231715365
2025-04-28 14:33:17,241 INFO Sampled n_switches -> 3
2025-04-28 14:33:17,241 INFO Sampled layer_list -> [0, 1, 2, 3, 4, 5, 6]
2025-04-28 14:33:18,807 INFO cycles_added: 8
2025-04-28 14:33:18,807 INFO convex_layers_used: [1, 2, 3]
2025-04-28 14:33:20,109 INFO cycles_added: 10
2025-04-28 14:33:20,109 INFO convex_layers_used: [1, 2, 3]
2025-04-28 14:33:23,678 INFO Sampled n_slack_busses -> 2
2025-04-28 14:33:24,423 ERROR Failed to create line 6178--5529:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,423 ERROR Failed to create line 6178--5382:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,423 ERROR Failed to create line 6178--6190:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,565 ERROR Failed to create line 5743--5529:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,565 ERROR Failed to create line 5743--7534:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,647 ERROR Failed to create line 5385--6061:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,648 ERROR Failed to create line 5385--5540:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,812 ERROR Failed to create line 7522--7529:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,813 ERROR Failed to create line 7522--9180:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:24,813 ERROR Failed to create line 7522--6064:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:25,085 INFO Sampled standard_cables -> standard_cable_1
2025-04-28 14:33:25,466 INFO Sampled n_slack_busses -> 1
2025-04-28 14:33:26,169 ERROR Failed to create line 9197--8690:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,181 ERROR Failed to create line 7386--8696:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,243 ERROR Failed to create line 7399--8676:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,272 ERROR Failed to create line 8696--8672:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,277 ERROR Failed to create line 8697--8088:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,416 ERROR Failed to create line 8641--8654:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,609 ERROR Failed to create line 8675--8686:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,627 ERROR Failed to create line 8687--8690:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:26,681 INFO Sampled standard_cables -> standard_cable_3
2025-04-28 14:33:29,740 INFO [Worker 32612] Saving graph graph_24298691593c42cebe8122816c146f32_mod_a to data\28042025_range-100-100_3\original\networkx_graphs
2025-04-28 14:33:30,766 INFO Power flow failed for graph_bc1b3edb1ff34ab18cdc18a02b3e031f@2025-02-13 08:45:00
2025-04-28 14:33:36,237 INFO cycles_added: 2
2025-04-28 14:33:36,237 INFO convex_layers_used: [0, 1, 2, 3, 4, 5, 6]
2025-04-28 14:33:40,039 INFO Sampled n_slack_busses -> 4
2025-04-28 14:33:40,939 ERROR Failed to create line 1198--9167:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:40,948 ERROR Failed to create line 1200--9171:Unknown: 'r_ohm_per_km'
2025-04-28 14:33:41,411 INFO Sampled standard_cables -> standard_cable_1
2025-04-28 14:33:44,458 INFO [Worker 34068] Saving graph graph_73b564305f5d45eb8434b01590134a55_mod_a to data\28042025_range-100-100_3\original\networkx_graphs
2025-04-28 14:33:45,657 INFO Finished: {'total': 3, 'successful': 2, 'failed': 1}
